### ISSUE TITLE
Don't work with more than one device

### ISSUE THREAD

**Issue by neworld** [vigilancer/android-app-run-gradle-plugin#1]
Most of the time I am connected with more than one device. I tried this plugin and got:

```
Starting process 'command '/Users/neworld/android/sdk/platform-tools/adb''. Working directory: /Users/neworld/projects/vinted/android/application Command: /Users/neworld/android/sdk/platform-tools/adb shell monkey -p com.vinted.global.dev -c android.intent.category.LAUNCHER 1
Successfully started process 'command '/Users/neworld/android/sdk/platform-tools/adb''
error: more than one device/emulator
```

I am using [ninja-adb](https://github.com/romannurik/env/blob/master/bin/ninja-adb) to send commands for all devices. Maybe similar approach could work for you

**Comment by vigilancer** [comment]
@neworld  thanks, I'm aware of this.
It's on my list, will handle in a couple of days.

**Comment by neworld** [comment]
I can't wait for it. BTW, here is another solution: use [`ConnectedDeviceProvider`](https://android.googlesource.com/platform/tools/base/+/master/build-system/gradle-core/src/main/groovy/com/android/build/gradle/internal/tasks/InstallVariantTask.java#93). `ConnectedDeviceProvider` looks like public API

**Comment by vigilancer** [comment]
@neworld thanks for the tip, ConnectedDeviceProvider is a nice find.
Anyway, new version 1.1.0 now works with multiple connected devices as expected.

**Comment by neworld** [comment]
Amazing! It works
